apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ricardo-advanceweb-db-pvc
  namespace: ricardo-advancedweb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi